### PR TITLE
Adding new problem

### PR DESCRIPTION
**Pull request by Felix-Egan**
For assignment 3 of SF-1

### CODE REVIEW

**Comment by WalrusInACan** [comment]
Everything looks super duper really fantasitic good.

**Comment by Felix-Egan** [comment]
# PR opened again:
Added new Coding-Cat problem (`flatten-list`). I also want to test the use of dictionaries as input/outputs in the `io.json` file. Formatting might need a bit of work (dimension wise) since the inputs are quite large character-wise. Please comment here if the inputs/outputs are oversized in the input/output tab and a modification PR will swiftly be opened. Have a great day!

**Comment by emaj9** [comment]
see conflicts @Felix-Egan

**Comment by Felix-Egan** [comment]
conflicts resolved.
cause: Problem from Assignment 3 had Matching Name to other submission (Pranjwal's) 
fix: renamed my folder submission: `remove vowels` -> `remove-vowels-2`

**Pull request merged**
