### PR TITLE
Adding new problem

### PR DESCRIPTION
**Pull request by DavidHack07**
Adding new problem

### CODE REVIEW

**Comment by khanz00024** [comment]
everything seems fine but shouldnt the category be strings instead of logic or logic 2

**Comment by DavidHack07** [comment]
> everything seems fine but shouldnt the category be strings or strings 2 instead of logic

yes i'll change that right away

**Comment by khanz00024** [comment]
but i am a bit confused about the problem....like why p does not repeat but r does when the programming is the input

**Comment by DavidHack07** [comment]
> but i am a bit confused about the problem....like why p does not repeat but r does when the programming is the input

because p is the first integer while the letter r is letter #2 as denoted when the function is called with "n" as 2.
If the input was 1 then every letter would be doubled but 2 means every other. The count restarts when the n-th number is reached, which is 2 in this case. 
(Programming,2) -> p r r o g g r a a m m m i n n g
(Programming,2) -> 1 22 1 2 2 1 2 2 1  2  2 1 2 2 1

**Comment by khanz00024** [comment]
but computers count from 0

**Comment by DavidHack07** [comment]
> but computers count from 0

but i assume the program would not be used by a computer or a programmer who has that knowledge. I assume that a random joe wants to doubled every n-th character and so they touch the buttons on the computer and boom. So if you ask someone what the 2nd letter of the word programming is they would respond with "r".

**Comment by DavidHack07** [comment]
> > but computers count from 0
> 
> but i assume the program would not be used by a computer or a programmer who has that knowledge. I assume that a random joe wants to doubled every n-th character and so they touch the buttons on the computer and boom. So if you ask someone what the 2nd letter of the word programming is they would respond with "r".

i will make it clearer in the instructions

**Comment by khanz00024** [comment]
ok then i think its alright ...make sure to submit the link on moodle

**Review by khanz00024 — COMMENTED** [review]
everything's fine

**Comment by khanz00024** [comment]
make sure you make a comment on the review changes section

**Pull request merged**
