### PR TITLE
Mutations for ordered_sequence

### PR DESCRIPTION
**Pull request by janiepunski**

### CODE REVIEW

**Comment by AdamI-7567** [comment]
Janie, you're missing mutations 4 and 5

**Comment by AdamI-7567** [comment]
Janie, your function definition differs from the one I made for this exercise

**Comment by AdamI-7567** [comment]
And you're still missing mutations 4 and 5

**Comment by emaj9** [comment]
mutation 2 will crash the program. the mutations cannot crash the program.

**Pull request closed without merging**
