### PR TITLE
Mutations for ordered_sequence

### PR DESCRIPTION
**Pull request by AdamI-7567**

### CODE REVIEW

**Comment by janiepunski** [comment]
You're supposed to make mutations for my problem (remove vowels once)

**Comment by AdamI-7567** [comment]
Just finished doing the right one

**Comment by janiepunski** [comment]
in your mutation 3, there's never going to be a correct solution

**Comment by AdamI-7567** [comment]
Done an other one for mutation 3.

**Comment by emaj9** [comment]
adam you need to delete the files you weren't supposed to write

**Pull request merged**
