### PR TITLE
Assignment 4

### PR DESCRIPTION
**Pull request by nicoleslanina**
6 mutations and 2 different solutions for nghi's problem (Longest-common-substring)

### CODE REVIEW

**Comment by nghidd1110** [comment]
Mutation 1 doesn't crash and is right for some cases. Which is good

**Comment by nghidd1110** [comment]
Mutation 2 hasn't crash for any test cases I tried but it does fail certain test cases

**Comment by nghidd1110** [comment]
Mutation 3 doesn't crash in any case, it simply does another function then what the question asks for!

**Comment by nghidd1110** [comment]
Mutation 4 is all good, since it can only catches the first common substring when there is another substring that is longer!

**Comment by nghidd1110** [comment]
Mutation 5 is fine since it doesn't crash for any test case, the reason why it fails is that it accumulates all the the similar symbols instead of substring

**Comment by nghidd1110** [comment]
All the suggested solutions give the right answers for all of my test cases
All good :)

**Comment by emaj9** [comment]
Astounding job both of you. you went above and beyond and really respected the PR process. bravo @nghidd1110 @nicoleslanina

**Pull request merged**
