### PR TITLE
Adding new problem

### PR DESCRIPTION
**Pull request by nghidd1110**
For assignment 3 of SF-1

### CODE REVIEW

**Comment by khanz00024** [comment]
comments working

**Comment by emaj9** [comment]
great, great question truly

**Comment by emaj9** [comment]
@nghidd1110  can you edit the meta to say this is a list-3 problem and difficulty: very-hard? lmk when its done

**Comment by nghidd1110** [comment]
@emaj9 i will and i'll let you know when im done!

**Comment by nghidd1110** [comment]
@emaj9 i just modified it

**Pull request merged**
