### PR TITLE
Adding new problem

### PR DESCRIPTION
**Pull request by AdamI-7567**
For assignment 3 of SF-1

### CODE REVIEW

**Review by Loic-Arthur-MQP — COMMENTED** [review]
Need adjustments at level of the input in the io.json file

**Comment by Loic-Arthur-MQP** [comment]
Verified, Certified. Might be completely safe.

**Comment by Loic-Arthur-MQP** [comment]
Verified, Certified, Reverified, and Recertified. Should be completely safe.

**Comment by emaj9** [comment]
good job gentlement

**Pull request merged**
