### PR TITLE
Adding mutations for Associate's problem (Adjacent Vowels)

### PR DESCRIPTION
**Pull request by Loic-Arthur-MQP**

### CODE REVIEW

**Comment by Loic-Arthur-MQP** [comment]
My partner said to have verified it

**Comment by Loic-Arthur-MQP** [comment]
@fdrgrn Please confirm the check

**Comment by fdrgrn** [comment]
Sorry I did it through direct messages. Yes, all the mutations check out and are all common mistakes someone might make!

**Comment by fdrgrn** [comment]
Overall, I think all the work is great!

**Comment by emaj9** [comment]
@Loic-Arthur-MQP thanks for doing 2

**Pull request merged**
