### PR TITLE
Adding new problem

### PR DESCRIPTION
**Pull request by JM-The-4th**
For assignment 3 of SF-1

### CODE REVIEW

**Comment by jeqcsix** [comment]
I see in the description that you are asking the user to print an output (which you show in your `starter.py` file with `print(____, end= " ")`). Coding Cat only checks the return value of the function to see if it matches with the output in `io.json`, so making the user return a list of numbers instead of printing the sequence would be well-suited for this problem in my opinion.

**Comment by JM-The-4th** [comment]
> I see in the description that you are asking the user to print an output (which you show in your `starter.py` file with `print(____, end= " ")`). Coding Cat only checks the return value of the function to see if it matches with the output in `io.json`, so making the user return a list of numbers instead of printing the sequence would be well-suited for this problem in my opinion.

I managed to incorporate a list into the required answer while keeping the print demand intact. Shouldn't make the question that much harder as only two extra line codes are required in the idealized solution.
I realize that it would be annoying to check if the print statement is correct, so I may remove it entirely.

**Comment by jeqcsix** [comment]
Looks great 👌

**Comment by emaj9** [comment]
fantastic

**Pull request merged**
